### ISSUE TITLE
Övergripande krav för VG

### ISSUE THREAD

**Issue by Ranchino** [davidyanis/ShopRims#20]
Webbplatsen som slutprojektet resulterar i skall vara responsiv 
Webbplatsen skall ha en fullt fungerande e-handel 
(Betalning och liknande skall fungera men kan vara kopplade till test-konton) 
Webbplatsen skall utnyttja cache för att ladda sidor snabbt 
Frontend för webbplatsen skall vara optimerad för att ladda snabbt.
Browser cachning skall utnyttjas 
Bilder skall använda sig av tumnaglar i lagom storlek, så att inte onödigt tunga bilder 
laddas in. 
Javascript och CSS skall minifieras.

**Comment by davidyanis** [comment]
KLAR
