### ISSUE TITLE
Ni skall bygga ett eget plugin för leveransmetod

### ISSUE THREAD

**Issue by Ranchino** [davidyanis/ShopRims#21]
o Det leveransalternativet skall vara frakt med bud
Detta alternativ skall alltid kosta och det skall vara möjligt att ställa in pris i admin. 
På er e-handel skall ni ha ställt in 3 olika fraktklasser. 
Baserat på vilken fraktklass de produkter man har i varukorgen har så skall 
leveransen kosta olika mycket. 
Det skall gå att ställa in pris för varje fraktklass. 
Den tyngsta produkten i varukorgen avgör vilket pris leveransen får.

**Comment by davidyanis** [comment]
klar
