### ISSUE TITLE
Ni skall bygga ett eget plugin för betalning

### ISSUE THREAD

**Issue by Ranchino** [davidyanis/ShopRims#22]
o Betalningsmetoden skall vara betalning via faktura.
För att få lov att betala via faktura måste användaren mata in sitt personnummer. 
Personnummer skall matas in i ett fält i kassan. 
Om inget personnummer angivits skall ett felmeddelande presenteras när 
man försöker genomföra betalning. 
Personnumret skall valideras med hjälp av Luhn-algoritmen. 
(https://sv.wikipedia.org/wiki/Luhn-algoritmen) 

• Om det är ett ogiltigt personnummer skall ett felmeddelande presenteras.

**Comment by davidyanis** [comment]
klar
