### ISSUE TITLE
Ni skall bygga ett andra eget plugins för leverans 

### ISSUE THREAD

**Issue by Ranchino** [davidyanis/ShopRims#23]
E-handeln skall ha ett leveransalternativ för att hämta upp leverans i butik.
I kassan skall man kunna välja i vilken butik man vill hämta ut sin order.

• Butikerna som kan väljas skall vara samma som listas på sidan med
företagets butiker.

Detta leveransalternativ skall vara gratis vid order över ett visst belopp. Det 
skall gå att ställa in vilket belopp som gäller. 
Om man inte överstiger beloppet skall leveransalternativet kosta och 
leveransavgiften skall gå att ställa in i admin.

**Comment by davidyanis** [comment]
klar
